name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Update version
      run: sudo apt-get update
    - name: Install Criterion
      run: sudo apt-get install libcriterion-dev
    - name: Install Additional libraries
      run: sudo apt-get install libbsd-dev
    - name: Build Unit Tests
      run: make test_build
    - name: Run Unit Tests
      run: make test
